Translation of Ud1110 IntroPy L301 Welcome To Lesson 3
udacity-china-translation/srt-translation-2017-07-Michelle-Wu11 pull request #1
Opened 2017-08-23 03:04 UTC by Michelle-Wu11

Translation of Ud1110 IntroPy L301 Welcome To Lesson 3
Subtitle ID: ikOWhrOUgLc

2017-08-23 13:30 UTC, ivylee0919 requested changes
做的不错 👍，可能对一些技术名词不是很了解
可以结合视频讲解内容，查询术语的翻译，可以查询词汇表，在 README 中可以找到，如果词汇表中没有，可以在 slack 中询问，加油，再修改一次~💪

2017-08-23 13:30 UTC, ivylee0919 commented on locales/zh-cn/-ikOWhrOUgLc.srt
> +到目前为止 我们的项目已经处理过单独的整数、浮点数和字符串
这里的 program 应该是指程序

2017-08-23 13:30 UTC, ivylee0919 commented on locales/zh-cn/-ikOWhrOUgLc.srt
> +我们还会学习如何用循环在数据集中重申
We'll also learn how to iterate through collections of data with loops.
我们还将学习如何使用循环对数据集进行**迭代**

2017-08-24 11:02 UTC, Michelle-Wu11 commented
@ivylee0919 已修改，请审阅！谢谢～

2017-08-27 15:49 UTC, ivylee0919 reviewed
- 18 行：an online encyclopedia 翻译为 “线上百科” 或者 “在线百科” 应该比 “网上百科” 要好
- 22 行：打钩->打勾
j0qfuunqym8.srt 这个文件里面的这两行需不需要修改一下？

2017-08-27 15:49 UTC, ivylee0919 commented on locales/zh-cn/j0qfuunqym8.srt
- 18 行：an online encyclopedia 翻译为 “线上百科” 或者 “在线百科” 应该比 “网上百科” 要好
- 22 行：打钩->打勾

2017-09-06 02:12 UTC, ivylee0919 approved these changes

2017-09-06 02:12 UTC, merged